### get all characters
GET http://localhost:8080/api/characters
### get character with id
GET http://localhost:8080/api/characters/4f5b6b7f-0bec-469e-8002-51bba40f0a5e
### get character not existing
GET http://localhost:8080/api/characters/c4804e0f-769e-4ab9-9ebe-0578fb4f00a5
### get all characters of specified series
GET http://localhost:8080/api/series/d0441997-9c76-4f94-a575-1f935084c3cb/characters
### get all characters of non existent series
GET http://localhost:8080/api/series/c4804e0f-769e-4ab9-9ebe-0578fb4f00a2/characters
### get singular character of specified series
GET http://localhost:8080/api/series/d0441997-9c76-4f94-a575-1f935084c3cb/characters/4f5b6b7f-0bec-469e-8002-51bba40f0a5e
### get singular character of non existent series
GET http://localhost:8080/api/series/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1/characters/565acba8-1f88-405a-bea7-5825cd19d4a1
### get non existent character of specified series
GET http://localhost:8080/api/series/8678e163-8228-4d8a-81f0-b14b19297032/characters/c4804e0f-769e-4ab9-9ebe-0578fb4f00a5
### get all seriess
GET http://localhost:8080/api/series
### get specific series
GET http://localhost:8080/api/series/df69c0c6-884c-42e2-985d-7663506a2294
### get non existent series
GET http://localhost:8080/api/series/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1
### create new character
PUT http://localhost:8080/api/characters/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1
Content-Type: application/json

{
  "id": "c4804e0f-769e-4ab9-9ebe-0578fb4f00b1",
  "name": "Bill",
  "age": 21,
  "series": "c4804e0f-769e-4ab9-9ebe-0578fb4f00a6"

}
### create new character in non existent series
PUT http://localhost:8080/api/characters/c4804e0f-769e-4ab9-9ebe-0578fb4f00b3
Content-Type: application/json

{

}
### create new series
PUT http://localhost:8080/api/seriess/c4804e0f-769e-4ab9-9ebe-0578fb4f00a5
Content-Type: application/json

{

}
### get all characters of empty series
GET http://localhost:8080/api/seriess/c4804e0f-769e-4ab9-9ebe-0578fb4f00a5/ships
### update character
PATCH http://localhost:8080/api/characters/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1
Content-Type: application/json

{
}
### update non existent character
PATCH http://localhost:8080/api/characters/c4804e0f-769e-4ab9-9ebe-0578fb4f00c9
Content-Type: application/json

{

}
### update series
PATCH http://localhost:8080/api/seriess/c4804e0f-769e-4ab9-9ebe-0578fb4f00a5
Content-Type: application/json

{

}
### update non existent series
PATCH http://localhost:8080/api/seriess/c4804e0f-769e-4ab9-9ebe-0578fb4f00c9
Content-Type: application/json

{

}
### delete character
DELETE http://localhost:8080/api/characters/c4804e0f-769e-4ab9-9ebe-0578fb4f00b1
### delete non existent character
DELETE http://localhost:8080/api/characters/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1
### delete series
DELETE http://localhost:8080/api/seriess/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6
### delete non existent series
DELETE http://localhost:8080/api/seriess/c4804e0f-769e-4ab9-9ebe-0578fb4f00a1